### ISSUE TITLE
Implement CRUD functions for document api

### ISSUE THREAD

**Issue by Marktine** [DenoteMD/denote-md#21]

**Comment by chiro-hiro** [comment]
Are there any detail?

**Comment by Marktine** [comment]
I'll break this one down to multiple issues
- Create post api
- Get list posts api
- Get post by Id api
- Delete post api
- Put/Patch post api

**Comment by chiro-hiro** [comment]
@Marktine Why does it close?

**Comment by Marktine** [comment]
> @Marktine Why does it close?

I'm gonna split this issue to smaller issues so I think it's better if this one is closed.
