### ISSUE TITLE
Create UX/UI login form

### ISSUE THREAD

**Issue by tan-qui** [DenoteMD/denote-md#27]
## Including
- Username:
  - Type: text 
  - Component: input 
  - Validator: 8-16 characters, not include special character.
- Password:
  - Type: password
  - Component: input
  - Validator: 8-32 characters, must include at least 1 uppercase letter, 1 special character, 1 number.

**Comment by chiro-hiro** [comment]
@tan-qui For `username` what if I chose `foo_bar` or `foo.bar`? how about number? and case sensitive?

**Comment by Marktine** [comment]
So `tan-qui` is now out of the team now, I'm gonna handle this one.
